### ISSUE TITLE
Crashes on big log file

### ISSUE THREAD

**Issue by mauvm** [kukua/concava-stats#1]
Log file size was around 450MB.

```
$ docker-compose logs
...
stats_1 | > concava-stats@0.1.0 start /data
stats_1 | > node lib/js/server.js
stats_1 | 
stats_1 | Listening on port 8080
stats_1 | Error: toString failed
stats_1 |     at Buffer.toString (buffer.js:382:11)
stats_1 |     at Object.fs.readFileSync (fs.js:461:33)
stats_1 |     at /data/lib/js/server.js:61:27
stats_1 |     at /data/node_modules/node-parallel/index.js:43:5
stats_1 |     at /data/node_modules/node-parallel/index.js:70:5
stats_1 |     at Array.forEach (native)
stats_1 |     at Parallel.done (/data/node_modules/node-parallel/index.js:69:12)
stats_1 |     at /data/lib/js/server.js:119:4
stats_1 |     at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
stats_1 |     at next (/data/node_modules/express/lib/router/route.js:131:13)
stats_1 | [Error: Timeout 10000 reached]
stats_1 | _http_outgoing.js:350
stats_1 |     throw new Error('Can\'t set headers after they are sent.');
stats_1 |     ^
stats_1 | 
stats_1 | Error: Can't set headers after they are sent.
stats_1 |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:350:11)
stats_1 |     at ServerResponse.header (/data/node_modules/express/lib/response.js:718:10)
stats_1 |     at ServerResponse.send (/data/node_modules/express/lib/response.js:163:12)
stats_1 |     at /data/lib/js/server.js:165:8
stats_1 |     at Parallel.cb (/data/node_modules/node-parallel/index.js:65:8)
stats_1 |     at Parallel.done (/data/node_modules/node-parallel/index.js:68:42)
stats_1 |     at /data/lib/js/server.js:161:5
stats_1 |     at Parallel.cb (/data/node_modules/node-parallel/index.js:65:8)
stats_1 |     at /data/node_modules/node-parallel/index.js:36:25
stats_1 |     at null._onTimeout (/data/node_modules/node-parallel/index.js:77:5)
```

**Comment by mauvm** [comment]
This time 398MB.
